version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mentalia

  mentalia:
    build: .
    ports:
      - "5000:5000"  # ← ESTO FALTABA
    volumes:
      - .:/opt/mentalia
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
